server:
  port: 8081

spring:
  application:
    name: serve
  datasource:
    url: jdbc:mysql://localhost:3306/qqsystem?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  # XML 文件位置
  type-aliases-package: com.qqsystem.serve.entity  # 实体类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL