server:
  port: 8081

# 自定义配置
app:
  domain: http://localhost:8081

spring:
  application:
    name: serve
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: true
  datasource:
    url: jdbc:mysql://localhost:3306/qqsystem?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml  # XML 文件位置
  type-aliases-package: com.qqsystem.serve.entity  # 实体类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL
    map-underscore-to-camel-case: true  # 开启驼峰命名转换